# Generated by Django 3.0.4 on 2020-03-29 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers_auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 13, 31, 6, 762287), verbose_name='date published'),
        ),
    ]
